FROM golang:1.25-alpine

WORKDIR /app

RUN apk add --no-cache git ca-certificates

# Hot-reload tool
RUN go install github.com/air-verse/air@latest

COPY go.mod ./
COPY go.sum* ./
RUN go mod download

EXPOSE 8080

CMD ["air"]
